# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb318dec8ed2e95c70130015b68ec7b21318d17e5526a8820b73c35eccca5d4b3129d3df30e385cd65bd3acd24573ab0404301f76936917817b2b88339963378

test:
  secret_key_base: fb111604f86bc4a8e63e7ee9299201f216df5331d2f473bb5e64ac8102ac89574a1828a8a90da223717813f979f059e1fcb75cd666f807ec100b37015729e0d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
